### ISSUE TITLE
Issue on backup AOS6

### ISSUE THREAD

**Issue by ebcoelho** [jefvantongerloo/ansible-aos-demo#3]
(.venv) eduardo@Eduardos-MacBook-Pro ansible-aos-demo % cat inventory.yml 
all:
  hosts:
    NET-SWI-001:
      ansible_host: 10.48.0.3
      device_vendor: alcatel
      device_os: aos6

(.venv) eduardo@Eduardos-MacBook-Pro ansible-aos-demo % ssh admin@10.48.0.3
admin's password for keyboard-interactive method: 
admin's password for keyboard-interactive method: 
  
Welcome to the Alcatel-Lucent Enterprise OmniSwitch 6350
Software Version 6.7.2.122.R08 GA, September 04, 2020. 

Copyright (C) ALE USA Inc. 2014-2019. All rights reserved.

OmniSwitch(TM) is a trademark of Alcatel-Lucent Enterprise registered
in the United States Patent and Trademark Office.
  
-> exit
Connection to 10.48.0.3 closed.

(.venv) eduardo@Eduardos-MacBook-Pro ansible-aos-demo % cat inventory.yml  
all:
  hosts:
    NET-SWI-001:
      ansible_host: 10.48.0.3
      device_vendor: alcatel
      device_os: aos6

(.venv) eduardo@Eduardos-MacBook-Pro ansible-aos-demo % ansible-playbook backup-all.yml -v
**Using /Users/eduardo/Documents/Python/ansible-aos-demo/ansible.cfg as config file**

PLAY [Backup all devices] *******************************************************************************************************************************************

TASK [IMPORT >> backup configuration] *******************************************************************************************************************************
**included: /Users/eduardo/Documents/Python/ansible-aos-demo/backup-aos6.yml for NET-SWI-001**

TASK [AOS6 >> backup configuration] *********************************************************************************************************************************
**fatal: [NET-SWI-001]: FAILED! => changed=false 
  msg: 'Unsupported parameters for (ale_aos_command) module: command Supported parameters include: commands, host, password, port, sshconfig, timing, username'**

PLAY RECAP **********************************************************************************************************************************************************
**NET-SWI-001                : ok=1**    changed=0    unreachable=0    **failed=1**    skipped=0    rescued=0    ignored=0

**Comment by jefvantongerloo** [comment]
Converted command parameter to list to make compatible with latest Ansible collection
